eva_flask/app/main/forms.py
#-*- coding=utf-8 -*-
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import Required, length, Regexp


class AddComRecordForm(FlaskForm):
    """
    用户提交维修记录的表单
    """
    user = StringField(u'* 物主姓名:', validators=[Required(), length(2, 5, message=u'姓名只允许2-5个字符！')])
    phone = StringField(u'* 手机号:', validators=[Required(), length(6, 11, message=u'只允许6-11位数字'), Regexp('[0-9]')])
    problem = TextAreaField(u'* 简要描述您的问题:', validators=[Required()])
    computer_type = StringField(u'* 您的电脑型号:', validators=[Required()])
    computer_password = StringField(u'您的电脑密码（可不填）:')
    submit = SubmitField(u'提交')

class AddEleRecordForm(FlaskForm):
    """
    用户提交维修记录的表单
    """
    user = StringField(u'* 物主姓名:', validators=[Required(), length(2, 5, message=u'姓名只允许2-5个字符！')])
    phone = StringField(u'* 手机号:', validators=[Required(), length(6, 11, message=u'只允许6-11位数字'), Regexp('[0-9]')])
    problem = TextAreaField(u'* 简要描述您的问题:', validators=[Required()])
    ele_type = StringField(u'* 您的电器类型:', validators=[Required()])
    submit = SubmitField(u'提交')


class GetRandomIdForm(FlaskForm):
    """
    序号相关的表单
    """
    random_id = StringField(u'请输入您的序列号：', validators=[Required()])
    submit = SubmitField(u'确认取回')

class AddCommentForm(FlaskForm):

    comment = TextAreaField(u'* 填写你的表白:', validators=[Required(),length(1, 64)])
    submit = SubmitField(u'提交')

app/main/__init__.py
# -*- coding=utf-8 -*-
from flask import Blueprint
import sys
reload(sys)
sys.setdefaultencoding('utf8')

main = Blueprint('main', __name__)

from . import views, errors

app/main/views.py
#-*- coding=utf-8 -*-
from flask import render_template, flash, redirect, url_for, request, session, make_response
from . import main
from flask_login import login_required, current_user, login_user, logout_user
from .forms import LoginForm,AddCommentForm,AddComRecordForm, GetRandomIdForm,AddEleRecordForm,ArrangeForm
from ..models import Record,Erecord,Unid,Comment,Article,Category,User
from .. import db
from datetime import datetime
import random
import string
from functools import wraps
from sqlalchemy import func
import sys
reload(sys)
sys.setdefaultencoding('utf8')

def Public(func):#公用账号 权限号为2017
    @wraps(func)
    def ADMIN(*args, **kwargs):
        PER = User.query.filter_by(name=session.get('name')).first()
        if PER.premission==2017:
            return func(*args, **kwargs)
        else:
            flash(u'你不是管理员')
            return redirect(url_for('main.index'))
    return ADMIN

def Admin(func):#管理员账号 权限号为2008
    @wraps(func)
    def ADMIN(*args, **kwargs):
        PER = User.query.filter_by(name=session.get('name')).first()
        if PER.premission==2008:
            return func(*args, **kwargs)
        else:
            flash(u'你不是管理员')
            return redirect(url_for('main.index'))
    return ADMIN

def Su(func):#超级管理员账号 权限号为1984
    @wraps(func)
    def ADMIN(*args, **kwargs):
        PER = User.query.filter_by(name=session.get('name')).first()
        if PER.premission==1984:
            return func(*args, **kwargs)
        else:
            flash(u'你不是管理员')
            return redirect(url_for('main.index'))
    return ADMIN


@main.route('/')
def index():
    clist = Category.query.all()
    alist = Article.query.all()
    return render_template('main/index.html',clist=clist,alist=alist)


@main.route('/user/amend', methods=['GET', 'POST'])
def user_amend():
    """
    用户添加维修记录
    :return:
    """
    dayOfWeek = datetime.today().weekday()
    type = request.args.get('type')
    if type == '2':
        form = AddEleRecordForm()
    else:
        form = AddComRecordForm()
    # alist = Record.query.all()
    if form.validate_on_submit():
        unid = Unid(random_id = string.join(
            random.sample(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'], 5)).replace(' ', ''))
        try:
            db.session.add(unid)
            db.session.commit()
        except:
            db.session.rollback()
            flash(u'随机码生成失败')
        if type == '2':
            erecord = Erecord(user=form.user.data, phone=form.phone.data, problem=form.problem.data,
                              create_time=datetime.now(), ele_type=form.ele_type.data, random_id=unid.random_id)
        else:
            record = Record(user=form.user.data, phone=form.phone.data, problem=form.problem.data,
                            create_time=datetime.now(),
                            computer_type=form.computer_type.data, computer_password=form.computer_password.data,
                            random_id=unid.random_id)
        i = 1
        while(i):
            try:
                if type == '2':
                    db.session.add(erecord)
                    db.session.commit()
                    flash(u'记录添加成功,您的随机码是 %s, 请务必截图保存' % erecord.random_id)
                else:
                    db.session.add(record)
                    db.session.commit()
                    flash(u'记录添加成功,您的随机码是 %s, 请务必截图保存' % record.random_id)
                i = 0
                return redirect(url_for('main.user_verify', random_id=unid.random_id))
            except:
                db.session.rollback()
    return render_template('main/amend.html', form=form)


@main.route('/user/verify/<int:random_id>', methods=['GET', 'POST'])
def user_verify(random_id):
    """
    用户确认物品取回
    :return:
    """
    form = GetRandomIdForm(random_id=random_id)
    if form.validate_on_submit():
        random_id = form.random_id.data
        record = Record.query.filter(Record.random_id == random_id).first()
        if record is None:
            erecord = Erecord.query.filter(Erecord.random_id == random_id).first()
            erecord.verify = True
            db.session.add(erecord)
            db.session.commit()
            flash(u'已确认取回')
        else:
            try:
                record.verify = True
                db.session.add(record)
                db.session.commit()
                flash(u'已确认取回')
            except:
                db.session.rollback()
                flash(u'未知错误')
        return redirect(url_for('main.user_amend'))
    return render_template('main/verify.html', form=form)


@main.route('/user/verify', methods=['GET', 'POST'])
def user_Verify():
    """
    用户确认物品取回
    :return:
    """
    form = GetRandomIdForm()
    if form.validate_on_submit():
        random_id = form.random_id.data
        record = Record.query.filter(Record.random_id == random_id).first()
        if record is None:
            erecord = Erecord.query.filter(Erecord.random_id == random_id).first()
            erecord.verify = True
            db.session.add(erecord)
            db.session.commit()
            flash(u'已确认取回')
        else:
            try:
                record.verify = True
                db.session.add(record)
                db.session.commit()
                flash(u'已确认取回')
            except:
                db.session.rollback()
                flash(u'未知错误')
        return redirect(url_for('main.user_amend'))
    return render_template('main/verify.html', form=form)

@main.route('/comment', methods=['GET', 'POST'])
def comment():
    form = AddCommentForm()
    if form.validate_on_submit():
        comment = Comment(comment = form.comment.data,create_time=datetime.now())
        i = 1
        while(i):
            try:
                db.session.add(comment)
                db.session.commit()
                flash(u'评论提交成功')
                i = 0
                return redirect(url_for('main.index'))
            except:
                db.session.rollback()
    return render_template('main/comment.html', form=form)

@main.route('/Innerlogin', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        session['name'] = form.username.data
        user = User.query.filter_by(name=form.username.data).first()
        session['id']=user.id
        if user is not None and user.verify_password(form.password.data):
            login_user(user)
            if user.premission==1984:
                return redirect(request.args.get('next') or url_for('main.SuIndex'))
            if user.premission==2008:
                return redirect(request.args.get('next') or url_for('main.AdminIndex'))
            if user.premission==1:
                return redirect(request.args.get('next') or url_for('main.innerIndex'))
        flash(u'用户密码不正确')
    return render_template('main/login.html', form=form)

@main.route('/Adminindex/arrange', methods=['GET'])
@Admin
def doarrange():

    return 0


@main.route('/Adminindex', methods=['GET'])
@Admin
def AdminIndex():
    user = User.query.filter_by(id=session.get('id')).first()
    group = "Wrong"
    arrange = "暂无安排"
    if user.arrangewant == '00':
        arrange = "暂未安排"
    day = user.arrangewant[0]
    time = user.arrangewant[1]
    if day == '1':
        arrange = "星期一"
    if day == '2':
        arrange = "星期二"
    if day == '3':
        arrange = "星期三"
    if day == '4':
        arrange = "星期四"
    if day == '5':
        arrange = "星期五"
    if day == '6':
        arrange = "星期六"
    if day == '7':
        arrange = "星期日"
    if time == '1':
        arrange = arrange + '第一班'
    if time == '2':
        arrange = arrange + '第二班'
    if time == '3':
        arrange = arrange + '第三班'

    if (user.group == 1):
        group = "电脑部"
    if (user.group == 2):
        group = "电器部"
    if (user.group == 3):
        group = "文宣部"
    if (user.group == 4):
        group = "财外部"
    if (user.group == 5):
        group = "人资部"

    return render_template('main/innerindex.html',
                           name=user.name,
                           tel=user.tel,
                           group=group,
                           arrange=arrange)

@main.route('/Suindex', methods=['GET'])
@Su
def SuIndex():
    user = User.query.filter_by(id=session.get('id')).first()
    group = "Wrong"
    arrange = "暂无安排"
    if user.arrangewant == '00':
        arrange = "暂未安排"
    day = user.arrangewant[0]
    time = user.arrangewant[1]
    if day == '1':
        arrange = "星期一"
    if day == '2':
        arrange = "星期二"
    if day == '3':
        arrange = "星期三"
    if day == '4':
        arrange = "星期四"
    if day == '5':
        arrange = "星期五"
    if day == '6':
        arrange = "星期六"
    if day == '7':
        arrange = "星期日"
    if time == '1':
        arrange = arrange + '第一班'
    if time == '2':
        arrange = arrange + '第二班'
    if time == '3':
        arrange = arrange + '第三班'

    if (user.group == 1):
        group = "电脑部"
    if (user.group == 2):
        group = "电器部"
    if (user.group == 3):
        group = "文宣部"
    if (user.group == 4):
        group = "财外部"
    if (user.group == 5):
        group = "人资部"

    return render_template('main/innerindex.html',
                           name=user.name,
                           tel=user.tel,
                           group=group,
                           arrange=arrange)

@main.route('/read/', methods=['GET'])
def read():
    a = Article.query.filter_by(id=request.args.get('id')).first()
    if a is not None:
        return render_template('main/read.html', a=a)
    flash(u'未找到相关文章')
    return redirect(url_for('main.index'))


@main.route('/inner', methods=['GET'])
@login_required
def innerIndex():
    user = User.query.filter_by(id=session.get('id')).first()
    group="Wrong"
    arrange="暂无安排"
    if user.arrangewant=='00':
        arrange="暂未安排"
    day=user.arrangewant[0]
    time=user.arrangewant[1]
    if day=='1':
        arrange="星期一"
    if day=='2':

eva_flask/app/main/__init__.py
# -*- coding=utf-8 -*-
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

eva_flask/app/main/views.py
#-*- coding=utf-8 -*-
from flask import render_template, flash, redirect, url_for, request
from . import main
from .forms import AddCommentForm,AddComRecordForm, GetRandomIdForm,AddEleRecordForm
from ..models import Record,Erecord,Unid,Comment,Article,Category
from .. import db
from datetime import datetime
import random
import string


@main.route('/')
def index():
    clist = Category.query.all()
    alist = Article.query.all()
    return render_template('main/index.html',clist=clist,alist=alist)


@main.route('/user/amend', methods=['GET', 'POST'])
def user_amend():
    """
    用户添加维修记录
    :return:
    """
    dayOfWeek = datetime.today().weekday()
    type = request.args.get('type')
    if type == '2':
        form = AddEleRecordForm()
    else:
        form = AddComRecordForm()
    # alist = Record.query.all()
    if form.validate_on_submit():
        unid = Unid(random_id = string.join(
            random.sample(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'], 5)).replace(' ', ''))
        try:
            db.session.add(unid)
            db.session.commit()
        except:
            db.session.rollback()
            flash(u'随机码生成失败')
        if type == '2':
            erecord = Erecord(user=form.user.data, phone=form.phone.data, problem=form.problem.data,
                              create_time=datetime.now(), ele_type=form.ele_type.data, random_id=unid.random_id)
        else:
            record = Record(user=form.user.data, phone=form.phone.data, problem=form.problem.data,
                            create_time=datetime.now(),
                            computer_type=form.computer_type.data, computer_password=form.computer_password.data,
                            random_id=unid.random_id)
        i = 1
        while(i):
            try:
                if type == '2':
                    db.session.add(erecord)
                    db.session.commit()
                    flash(u'记录添加成功,您的随机码是 %s, 请务必截图保存' % erecord.random_id)
                else:
                    db.session.add(record)
                    db.session.commit()
                    flash(u'记录添加成功,您的随机码是 %s, 请务必截图保存' % record.random_id)
                i = 0
                return redirect(url_for('main.user_verify', random_id=unid.random_id))
            except:
                db.session.rollback()
    return render_template('main/amend.html', form=form)


@main.route('/user/verify/<int:random_id>', methods=['GET', 'POST'])
def user_verify(random_id):
    """
    用户确认物品取回
    :return:
    """
    form = GetRandomIdForm(random_id=random_id)
    if form.validate_on_submit():
        random_id = form.random_id.data
        record = Record.query.filter(Record.random_id == random_id).first()
        if record is None:
            erecord = Erecord.query.filter(Erecord.random_id == random_id).first()
            erecord.verify = True
            db.session.add(erecord)
            db.session.commit()
            flash(u'已确认取回')
        else:
            try:
                record.verify = True
                db.session.add(record)
                db.session.commit()
                flash(u'已确认取回')
            except:
                db.session.rollback()
                flash(u'未知错误')
        return redirect(url_for('main.user_amend'))
    return render_template('main/verify.html', form=form)


@main.route('/user/verify', methods=['GET', 'POST'])
def user_Verify():
    """
    用户确认物品取回
    :return:
    """
    form = GetRandomIdForm()
    if form.validate_on_submit():
        random_id = form.random_id.data
        record = Record.query.filter(Record.random_id == random_id).first()
        if record is None:
            erecord = Erecord.query.filter(Erecord.random_id == random_id).first()
            erecord.verify = True
            db.session.add(erecord)
            db.session.commit()
            flash(u'已确认取回')
        else:
            try:
                record.verify = True
                db.session.add(record)
                db.session.commit()
                flash(u'已确认取回')
            except:
                db.session.rollback()
                flash(u'未知错误')
        return redirect(url_for('main.user_amend'))
    return render_template('main/verify.html', form=form)

@main.route('/comment', methods=['GET', 'POST'])
def comment():
    form = AddCommentForm()
    if form.validate_on_submit():
        comment = Comment(comment = form.comment.data,create_time=datetime.now())
        i = 1
        while(i):
            try:
                db.session.add(comment)
                db.session.commit()
                flash(u'评论提交成功')
                i = 0
                return redirect(url_for('main.index'))
            except:
                db.session.rollback()
    return render_template('main/comment.html', form=form)

@main.route('/read/', methods=['GET'])
def read():
    a = Article.query.filter_by(id=request.args.get('id')).first()
    if a is not None:
        return render_template('main/read.html', a=a)
    flash(u'未找到相关文章')
    return redirect(url_for('main.index'))

app/templates/main/Adminindex.html
{% extends "main/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}
<div class="container-fluid">
	<div class="row-fluid">
		<div class="col-md-2">
			<ul class="nav nav-pills nav-stacked">
				<li class="nav-header">
					个人信息
				</li>
				<li class="active">
					<a href="{{ url_for('main.innerIndex') }}">首页</a>
				</li>
				<li>
					<a href="{{ url_for('main.arrange') }}">排班</a>
				</li>
				<li>
					<a href="{{ url_for('main.assign') }}">任务</a>
				</li>
				<li class="nav-header">
					功能列表
				</li>
				<li>
					<a href="{{ url_for('main.doarrange') }}">排班生成</a>
				</li>
				<li>
					<a href="{{ url_for('main.experience') }}">值班经验</a>
				</li>
				<li>
					<a href="{{ url_for('main.fince') }}">财务报销</a>
				</li>
                <li class="nav-header">
					管理功能
				</li>
				<li>
					<a href="{{ url_for('main.arrangewant') }}">排班修改</a>
				</li>
				<li>
					<a href="{{ url_for('main.experience') }}">值班经验总览</a>
				</li>
				<li>
					<a href="{{ url_for('main.fince') }}">财务报销总览</a>
				</li>
                <li>
					<a href="{{ url_for('main.fince') }}">任务发布</a>
				</li>
			</ul>
		</div>
        <div class="col-md-1">
        </div>
		<div class="col-md-9">
			<div class="row">
				<div >
					<h2 class="title-thin text-muted">个人信息</h2>
					<br/>
				</div>

                <div class="col-sm-6 clear-mrg">
                    <dl>
                        <dt class="text-upper">姓名</dt>
                        <dd>{{ name }}</dd>
						<br/>
                        <dt class="text-upper">电话</dt>
                        <dd>{{ tel }}</dd>
						<br/>
                        <dt class="text-upper">部门</dt>
                        <dd>{{ group }}</dd>
						<br/>
						<dt class="text-upper">排班</dt>
                        <dd>{{ arrange }}</dd>
						<br/>
                    </dl>
                </div><!-- .col-sm-6 -->
            </div>
		</div>
	</div>
</div>
{% endblock %}

app/templates/main/amend.html
{% extends "main/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}
    <div class="col-md-6">
        <h1>维修登记</h1>
        <hr>
        <div class="btn-group btn-group-lg" role="group" aria-label="...">
            <a href="{{ url_for('main.user_amend', type=1) }}" button type="button" class="btn btn-default" >电脑</a></abutton>
            <a href="{{ url_for('main.user_amend', type=2) }}" button type="button" class="btn btn-default">电器</a></button>
        </div>
        <br>
        <br>
        {{ wtf.quick_form(form) }}
    </div>
{% endblock %}

app/templates/main/base.html
{% extends "bootstrap/base.html" %}
{% block title %}E志者维修登记平台{% endblock %}

{% block head %}
{{ super() }}
<link rel="shortcut icon" href="{{ url_for('static', filename = 'favicon.ico') }}"
type="image/x-icon">
<link rel="icon" href="{{ url_for('static', filename = 'favicon.ico') }}"
type="image/x-icon">
    <style type="text/css">
		.scrollspy-example {
			height: 900px;
			overflow: auto;
			position: relative;
		}
	</style>
{% endblock %}


{% block navbar %}
<div class="navbar navbar-default" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">浙江大学学生E志者协会</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="/user/amend">我要维修</a></li>
                <li><a href="/user/verify">确认取回</a></li>
                <li><a href="{{ url_for('main.comment') }}">表白墙</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if 0==1 %}
                <li><a href="{{ url_for('admin.register') }}">注册</a></li>
                {% endif %}
                <li><a href="{{ url_for('admin.index') }}">管理员</a></li>
                <li><a href="{{ url_for('main.login') }}">内部登录</a></li>
            </ul>
        </div>
    </div>
</div>

{% endblock %}

{% block content %}
    <div class="container">
        {% for message in get_flashed_messages() %}
            <div class="alert alert-warning">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                {{ message }}
            </div>
        {% endfor %}
        {% block page_content %}{% endblock %}
    </div>
    <div class="footer">
        <ul class="list-inline text-center">
            <hr />
            <li>浙江大学东三-200 <strong><a href="//zjueva.cn/" >浙江大学学生E志者协会</a></strong>
                备案号：浙ICP备17008331号</li>
        </ul>
    </div>
{% endblock %}

app/templates/main/comment.html
{% extends "main/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}
    <div class="col-md-6">
        <h1>表白提交</h1>
        <hr>
        {{ wtf.quick_form(form) }}
    </div>
    <div class="col-md-6">
    </div>
{% endblock %}

app/templates/main/id.html
{% extends "main/base.html" %}

{% block page_content %}
<div class="container">
    <div class="page-header">
        <li><p>你的序列号是</p>{{ id }}</li>
        <li>请注意截图保存</li>
    </div>
</div>
{% endblock %}

app/templates/main/index.html
{% extends "main/base.html" %}

{% block content %}
<!--img src="{{ url_for('static', filename = 'main/backgroud.png') }}" alt="First slide"-->
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
          <!-- Indicators -->
          <ol class="carousel-indicators">
            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
            <li data-target="#carousel-example-generic" data-slide-to="2"></li>
          </ol>

          <!-- Wrapper for slides -->
          <div class="carousel-inner" role="listbox">
            <div class="item active">
              <img src="https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1503216871488&di=481fd3b30c4b7251954206a7c35b6453&imgtype=jpg&src=http%3A%2F%2Fimg1.imgtn.bdimg.com%2Fit%2Fu%3D321143402%2C194363490%26fm%3D214%26gp%3D0.jpg" alt="First slide" alt="...">
              <div class="carousel-caption">
                1
              </div>
            </div>
            <div class="item">
              <img src="https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1503216918747&di=f9218ac8950dd99eb120215173bcd31a&imgtype=0&src=http%3A%2F%2Fs9.knowsky.com%2Fbizhi%2Fl%2F5001-10000%2F2009528111954303053199.jpg" alt="...">
              <div class="carousel-caption">
                2
              </div>
            </div>
              <div class="item">
                <img src="https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1503216960910&di=b60386ac6d97306c96a965031325cc7e&imgtype=0&src=http%3A%2F%2Fs9.knowsky.com%2Fbizhi%2Fl%2F5001-10000%2F2009528111948265553116.jpg" alt="...">
                <div class="carousel-caption">
                  3
              </div>
              </div>
                 <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                  <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                  <span class="sr-only">Previous</span>
                </a>
                <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                  <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                  <span class="sr-only">Next</span>
                </a>
        </div>
        </div>
<div class="container">
  <div class="row">
    <div class="col-xs-10 col-md-10">
      <nav id="navbar-example" class="navbar navbar-default navbar-static" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button class="navbar-toggle" type="button" data-toggle="collapse"
                        data-target=".bs-js-navbar-scrollspy">
                    <span class="sr-only">切换导航</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">教程名称</a>
            </div>
            <div class="collapse navbar-collapse bs-js-navbar-scrollspy">
                <ul class="nav navbar-nav">
                    <li><a href="#video">社团视频</a></li>
                    <li><a href="#introduction">社团简介</a></li>
                    <li><a href="#history">我们的历史</a></li>
                </ul>
            </div>
        </div>
    </nav>
<div class="text-center" data-spy="scroll" data-target="#navbar-example" data-offset="0"
	 style="overflow:auto; position: relative;">
	<h1 id="video">社团视频</h1>
  <br>
	<div class="embed-responsive embed-responsive-16by9">
        <iframe class="embed-responsive-item" src="http://v.qq.com/iframe/player.html?vid=g01655y5lkz"></iframe>
    </div>
  <br><br><br>

    <h1 id="introduction">社团简介</h1>
  <br>
	<p style="font-size:x-large">
      E志者协会以“奉献爱心、服务群众”为己任，凝聚拥有电器维修爱好者的力量，以电气学院丰富的学科优势资源为依托，提供浙大学子展示自我、服务大众的平台，建设提高专业知识、交流技术经验的环境，全面提高会员的综合素质，近年来更是实现了由老的志愿者服务组织向新的社团组织发展的成功转型。E志者协会及其前身电气维修小组多次被评为校级志愿者先进（优秀）集体，还曾获得“浙江大学十大优秀志愿者服务集体”、“浙江省优秀志愿者服务队伍”。2006年，其便民利民服务项目被评为“省级青年志愿者服务工程”。2007年被列为“浙江大学大学生素质拓展基地创建单位”
	</p>
  <br><br><br>

	<h1 id="history">我们的历史</h1>
  <br>
	<p style="font-size:x-large">浙江大学学生E志者协会的前身是<br><br>
      1984年前电机系（现电气工程学院）的<br><br>
      学生（陈强等）创办的<br><br>
      <strong>电器维修小组</strong><br><br>
      在2008年9月正式成为校级学生社团<br><br>
      <img class="center block" src="{{ url_for('static', filename = 'main/history.jpg') }}" alt="history">
	</p>
</div>
    </div>
    <div class="col-xs-2 col-md-2">
        <br><br><br><br><br><br><br><br><br><br><br><br><br>
        <div class="panel panel-default">
          <div class="panel-heading">目录</div>
              <ul class="list-group">
                {% for foo in clist %}
                <a href="#" class="list-group-item">{{ foo.name }}</a>
                {% endfor %}
              </ul>
        </div>
        <br><br><br><br><br><br><br><br><br><br><br><br><br>
        <div class="panel panel-default">
          <div class="panel-heading">近期文章</div>
                <ul class="list-group">
                {% for foo in alist %}
                    <a href="{{ url_for('main.read' , id=foo.id) }}" class="list-group-item">{{ foo.title }}     {{ foo.create_time }}</a>
                {% endfor %}
                </ul>
        </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/main/read.html
{% extends 'main/base.html' %}
{% block page_content %}
<div class="page-header">
    <h2>{{ a.title }}</h2>
            <hr>
            <p>{{ a.create_time }} | {{ a.category.name }}</p>
        {% if a.body_html %}
            {{ a.body_html | safe }}
        {% else %}
            {{ a.body }}
        {% endif %}
</div>
{% endblock %}